### ISSUE TITLE
LFS limited

### ISSUE THREAD

**Issue by dandified** [agsiddhant/ForwardSurrogate_Mars_2D#1]
Hello! I want to clone this repo to learn about your work, but in the LFS part it shows below: 
`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`
Would you upload the LFS part to a google cloud or something? Like this repo: https://github.com/kehuantiantang/A-DNN-based-Semantic-Segmentation-for-Detecting-Weed-and-Crop/issues/1

**Comment by dandified** [comment]
Sorry, I'm new to git lfs, I just found that fork this repo can solve this problem. Thanks for your work!

**Comment by agsiddhant** [comment]
Ah great, thanks for figuring it out and posting a solution :)
